export default [
    {jpName:'ラグナ', enName:'ragna', abbrev:'TAG_RG'},
    {jpName:'ジン', enName:'jin', abbrev:'TAG_JI'},
    {jpName:'ノエル', enName:'noel', abbrev:'TAG_NO'},
    {jpName:'レイチェル', enName:'rachel', abbrev:'TAG_RC'},
    {jpName:'ハザマ', enName:'hazama', abbrev:'TAG_HZ'},
    {jpName:'テイガー', enName:'iron-tager', abbrev:'TAG_TG'},
    {jpName:'ニュー13', enName:'nu-13',abbrev: 'TAG_NU'},
    {jpName:'マコト', enName:'makoto', abbrev:'TAG_MK'},
    {jpName:'アズラエル', enName:'azrael', abbrev:'TAG_AZ'},
    {jpName: 'エス', enName:'es', abbrev:'TAG_ES'},
    {jpName: 'プラチナ', enName:'platinum', abbrev:'TAG_PL'},
    {jpName:'獣兵衛', enName:'jubei', abbrev:'TAG_JU'},
    {jpName:'ハクメン', enName:'hakumen', abbrev:'TAG_HK'},
    {jpName:'マイ＝ナツメ', enName:'Mai=Natsume', abbrev:'TAG_MA'},
    {jpName: 'イザヨイ', enName:'Izayoi', abbrev:'TAG_IZ'},
    {jpName:'ナイン', enName:'Nine=The=Phantom', abbrev:'TAG_NI'},
    {jpName:'鳴上悠', enName:'yu-narukami', abbrev:'TAG_YU'},
    {jpName:'花村陽介', enName: 'yosuke-hanamura', abbrev:'TAG_YO'},
    {jpName:'里中千枝', enName:'chie-satonaka',abbrev: 'TAG_CH'},
    {jpName:'天城雪子', enName: 'yukiko-amagi', abbrev:'TAG_YK'},
    {jpName: '巽完二', enName:'kanji-tatsumi', abbrev:'TAG_KA'},
    {jpName:'アイギス', enName: 'aegis', abbrev:'TAG_AG'},
    {jpName:'白鐘直斗', enName:'naoto-shirogane', abbrev:'TAG_NA'},
    {jpName: '桐条 美鶴', enName: 'Mitsuru Kirijo', abbrev:'TAG_MS'},
    {jpName: '真田明彦', enName: 'Akihiko Sanada', abbrev:'TAG_AK'},
    {jpName: 'ラビリス', enName: 'Labrys', abbrev:'TAG_LB'},
    {jpName: 'ハイド', enName:'hyde', abbrev:'TAG_HY'},
    {jpName: 'リンネ', enName:'linne', abbrev:'TAG_LN'},
    {jpName: 'ワレンシュタイン', enName: 'waldstein', abbrev:'TAG_WD'},
    {jpName:'ゴルドー', enName: 'gordeau', abbrev:'TAG_GD'},
    {jpName:'オリエ', enName:'orie', abbrev:'TAG_OR'},
    {jpName:'カーマイン', enName:'carmine', abbrev:'TAG_CR'},
    {jpName: 'ヴァチスタ', enName:'vatista', abbrev:'TAG_VA'},
    {jpName:'ユズリハ', enName:'Yuzuriha', abbrev:'TAG_YZ'},
    {jpName: 'ミカ・リターナ', enName:'Mika Returna', abbrev:'TAG_MI'},
    {jpName:'メルカヴァ', enName:'Merkava', abbrev:'TAG_MR'},
    {jpName: 'ルビー・ローズ', enName:'ruby-rose', abbrev:'TAG_RR'},
    {jpName:'ワイス・シュニー', enName: 'weiss-schnee', abbrev:'TAG_WS'},
    {jpName: 'ブレイク・ベラドンナ', enName:'blake-belladonna', abbrev:'TAG_BB'},
    {jpName: 'ヤン・シャオロン', enName:'yang-xiao-long', abbrev:'TAG_YX'},
]