const suggestions = [
    
    { label:'Ragna the Bloodedge'},
    { label: 'Jin Kisaragi'},
    { label: 'Rachel Alucard'},
    { label: 'Hazama'},
    { label: 'Noel Vermillion'},
    { label: 'Azrael'},
    { label: 'Iron Tager'},
    { label: 'Makoto Nanaya'},
    { label: 'ν-No.13-'},
    { label: 'Es'},
    { label: 'Platinum the Trinity'},
    { label: 'Jūbei'},
    { label: 'Hakumen'},
    { label: 'Nine the Phantom'},
    { label: 'Izayoi'},
    { label: 'Mai Natsume'},
    { label: 'Yū Narukami'},
    { label: 'Yōsuke Hanamura'},
    { label: 'Chie Satonaka'},
    { label: 'Yukiko Amagi'},
    { label: 'Kanji Tatsumi'},
    { label: 'Aegis'},
    { label: 'Naoto Shirogane'},
    { label: 'Mitsuru Kirijo'},
    { label: 'Akihiko Sanada'},
    { label: 'Labrys'},
    { label: 'Hyde'},
    { label: 'Linne'},
    { label: 'Waldstein'},
    { label: 'Gordeau'},
    { label: 'Orie'},
    { label: 'Carmine'},
    { label: 'Vatista'},
    { label: 'Yuzuriha'},
    { label: 'Merkava'},
    { label: 'Mika'},
    { label: 'Ruby Rose'},
    { label: 'Weiss Schnee'},
    { label: 'Blake Belladonna' },
    { label: 'Yang Xiao Long'},
];

export default suggestions